grails-app/domain/CarInsurance/Pregunta.groovy
package CarInsurance;

import javax.annotation.Resource;

import grails.rest.*;

@grails.rest.Resource(uri='/preguntas', formats=['json', 'xml'])
class Pregunta {
	
	String code
	
	String question
	
	int position
	
	Map<String,Integer> typeWeight
	
	public String toString() { return question }
} 

grails-app/views/pregunta/_form.gsp
<%@ page import="CarInsurance.Pregunta" %>



<div class="fieldcontain ${hasErrors(bean: preguntaInstance, field: 'code', 'error')} ">
	<label for="code">
		<g:message code="pregunta.code.label" default="Code" />
		
	</label>
	<g:textField name="code" value="${preguntaInstance?.code}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: preguntaInstance, field: 'position', 'error')} required">
	<label for="position">
		<g:message code="pregunta.position.label" default="Position" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="position" type="number" value="${preguntaInstance.position}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: preguntaInstance, field: 'question', 'error')} ">
	<label for="question">
		<g:message code="pregunta.question.label" default="Question" />
		
	</label>
	<g:textField name="question" value="${preguntaInstance?.question}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: preguntaInstance, field: 'typeWeight', 'error')} ">
	<label for="typeWeight">
		<g:message code="pregunta.typeWeight.label" default="Type Weight" />
		
	</label>
	
</div>

grails-app/views/pregunta/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pregunta.label', default: 'Pregunta')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-pregunta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-pregunta" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${preguntaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${preguntaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:preguntaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/pregunta/edit.gsp
<%@ page import="CarInsurance.Pregunta" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pregunta.label', default: 'Pregunta')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-pregunta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-pregunta" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${preguntaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${preguntaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:preguntaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${preguntaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/pregunta/index.gsp
<%@ page import="CarInsurance.Pregunta" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pregunta.label', default: 'Pregunta')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-pregunta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-pregunta" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="code" title="${message(code: 'pregunta.code.label', default: 'Code')}" />
					
						<g:sortableColumn property="position" title="${message(code: 'pregunta.position.label', default: 'Position')}" />
					
						<g:sortableColumn property="question" title="${message(code: 'pregunta.question.label', default: 'Question')}" />
					
						<g:sortableColumn property="typeWeight" title="${message(code: 'pregunta.typeWeight.label', default: 'Type Weight')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${preguntaInstanceList}" status="i" var="preguntaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${preguntaInstance.id}">${fieldValue(bean: preguntaInstance, field: "code")}</g:link></td>
					
						<td>${fieldValue(bean: preguntaInstance, field: "position")}</td>
					
						<td>${fieldValue(bean: preguntaInstance, field: "question")}</td>
					
						<td>${fieldValue(bean: preguntaInstance, field: "typeWeight")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${preguntaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/pregunta/show.gsp
<%@ page import="CarInsurance.Pregunta" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'pregunta.label', default: 'Pregunta')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-pregunta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-pregunta" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list pregunta">
			
				<g:if test="${preguntaInstance?.code}">
				<li class="fieldcontain">
					<span id="code-label" class="property-label"><g:message code="pregunta.code.label" default="Code" /></span>
					
						<span class="property-value" aria-labelledby="code-label"><g:fieldValue bean="${preguntaInstance}" field="code"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${preguntaInstance?.position}">
				<li class="fieldcontain">
					<span id="position-label" class="property-label"><g:message code="pregunta.position.label" default="Position" /></span>
					
						<span class="property-value" aria-labelledby="position-label"><g:fieldValue bean="${preguntaInstance}" field="position"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${preguntaInstance?.question}">
				<li class="fieldcontain">
					<span id="question-label" class="property-label"><g:message code="pregunta.question.label" default="Question" /></span>
					
						<span class="property-value" aria-labelledby="question-label"><g:fieldValue bean="${preguntaInstance}" field="question"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${preguntaInstance?.typeWeight}">
				<li class="fieldcontain">
					<span id="typeWeight-label" class="property-label"><g:message code="pregunta.typeWeight.label" default="Type Weight" /></span>
					
						<span class="property-value" aria-labelledby="typeWeight-label"><g:fieldValue bean="${preguntaInstance}" field="typeWeight"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:preguntaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${preguntaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>