grails-app/domain/CarInsurance/InsuranceType.groovy
package CarInsurance

public enum InsuranceType {

    todoRiesgo("TR","Todo Riesgo"), 
	responsabilidadCivil("RC","Responsabilidad Civil"),
	tercerosCompleto("TC","Terceros Completo"),
	tercerosCompletosFull("TCF","Terceros Completo Full"),
	tercerosCompletosFullGranizo("TCFG","Terceros Completo Full + Granizo")

	InsuranceType(String code, String description) { 
		this.description = description
		this.code = code
		}
    
	private final String description
	private final String code
    
	public String description() { return description }
	public String code() { return code }
	
	public String toString(){
		return this.description()
	}
}

grails-app/domain/smarty2/Insurance.groovy
package smarty2

import CarInsurance.InsuranceType;

class Insurance {

	InsuranceType insuranceType
	Integer price	// el precio conviene sacarlo de la poliza y relacionarlo a traves de la empresa o un Tarifador -eze
	String description
	String details
	
	static belongsTo= [company: InsuranceCompany]
	
    static constraints = {
    }
}

grails-app/controllers/smarty2/InsuranceCompanyController.groovy
package smarty2



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class InsuranceCompanyController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond InsuranceCompany.list(params), model:[insuranceCompanyInstanceCount: InsuranceCompany.count()]
    }

    def show(InsuranceCompany insuranceCompanyInstance) {
        respond insuranceCompanyInstance
    }

    def create() {
        respond new InsuranceCompany(params)
    }

    @Transactional
    def save(InsuranceCompany insuranceCompanyInstance) {
        if (insuranceCompanyInstance == null) {
            notFound()
            return
        }

        if (insuranceCompanyInstance.hasErrors()) {
            respond insuranceCompanyInstance.errors, view:'create'
            return
        }

        insuranceCompanyInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'insuranceCompanyInstance.label', default: 'InsuranceCompany'), insuranceCompanyInstance.id])
                redirect insuranceCompanyInstance
            }
            '*' { respond insuranceCompanyInstance, [status: CREATED] }
        }
    }

    def edit(InsuranceCompany insuranceCompanyInstance) {
        respond insuranceCompanyInstance
    }

    @Transactional
    def update(InsuranceCompany insuranceCompanyInstance) {
        if (insuranceCompanyInstance == null) {
            notFound()
            return
        }

        if (insuranceCompanyInstance.hasErrors()) {
            respond insuranceCompanyInstance.errors, view:'edit'
            return
        }

        insuranceCompanyInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'InsuranceCompany.label', default: 'InsuranceCompany'), insuranceCompanyInstance.id])
                redirect insuranceCompanyInstance
            }
            '*'{ respond insuranceCompanyInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(InsuranceCompany insuranceCompanyInstance) {

        if (insuranceCompanyInstance == null) {
            notFound()
            return
        }

        insuranceCompanyInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'InsuranceCompany.label', default: 'InsuranceCompany'), insuranceCompanyInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'insuranceCompanyInstance.label', default: 'InsuranceCompany'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/smarty2/InsuranceController.groovy
package smarty2



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class InsuranceController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Insurance.list(params), model:[insuranceInstanceCount: Insurance.count()]
    }

    def show(Insurance insuranceInstance) {
        respond insuranceInstance
    }

    def create() {
        respond new Insurance(params)
    }

    @Transactional
    def save(Insurance insuranceInstance) {
        if (insuranceInstance == null) {
            notFound()
            return
        }

        if (insuranceInstance.hasErrors()) {
            respond insuranceInstance.errors, view:'create'
            return
        }

        insuranceInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'insuranceInstance.label', default: 'Insurance'), insuranceInstance.id])
                redirect insuranceInstance
            }
            '*' { respond insuranceInstance, [status: CREATED] }
        }
    }

    def edit(Insurance insuranceInstance) {
        respond insuranceInstance
    }

    @Transactional
    def update(Insurance insuranceInstance) {
        if (insuranceInstance == null) {
            notFound()
            return
        }

        if (insuranceInstance.hasErrors()) {
            respond insuranceInstance.errors, view:'edit'
            return
        }

        insuranceInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Insurance.label', default: 'Insurance'), insuranceInstance.id])
                redirect insuranceInstance
            }
            '*'{ respond insuranceInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Insurance insuranceInstance) {

        if (insuranceInstance == null) {
            notFound()
            return
        }

        insuranceInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Insurance.label', default: 'Insurance'), insuranceInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'insuranceInstance.label', default: 'Insurance'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/insurance/_form.gsp
<%@ page import="smarty2.Insurance" %>



<div class="fieldcontain ${hasErrors(bean: insuranceInstance, field: 'company', 'error')} required">
	<label for="company">
		<g:message code="insurance.company.label" default="Company" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="company" name="company.id" from="${smarty2.InsuranceCompany.list()}" optionKey="id" required="" value="${insuranceInstance?.company?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: insuranceInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="insurance.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${insuranceInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: insuranceInstance, field: 'details', 'error')} ">
	<label for="details">
		<g:message code="insurance.details.label" default="Details" />
		
	</label>
	<g:textField name="details" value="${insuranceInstance?.details}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: insuranceInstance, field: 'insuranceType', 'error')} required">
	<label for="insuranceType">
		<g:message code="insurance.insuranceType.label" default="Insurance Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="insuranceType" from="${CarInsurance.InsuranceType?.values()}" keys="${CarInsurance.InsuranceType.values()*.name()}" required="" value="${insuranceInstance?.insuranceType?.name()}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: insuranceInstance, field: 'price', 'error')} required">
	<label for="price">
		<g:message code="insurance.price.label" default="Price" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="price" type="number" value="${insuranceInstance.price}" required=""/>
</div>

grails-app/views/insurance/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'insurance.label', default: 'Insurance')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-insurance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-insurance" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${insuranceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${insuranceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:insuranceInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/insurance/edit.gsp
<%@ page import="smarty2.Insurance" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'insurance.label', default: 'Insurance')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-insurance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-insurance" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${insuranceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${insuranceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:insuranceInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${insuranceInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/insurance/index.gsp
<%@ page import="smarty2.Insurance" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'insurance.label', default: 'Insurance')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-insurance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-insurance" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="insurance.company.label" default="Company" /></th>
					
						<g:sortableColumn property="description" title="${message(code: 'insurance.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="details" title="${message(code: 'insurance.details.label', default: 'Details')}" />
					
						<g:sortableColumn property="insuranceType" title="${message(code: 'insurance.insuranceType.label', default: 'Insurance Type')}" />
					
						<g:sortableColumn property="price" title="${message(code: 'insurance.price.label', default: 'Price')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${insuranceInstanceList}" status="i" var="insuranceInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${insuranceInstance.id}">${fieldValue(bean: insuranceInstance, field: "company")}</g:link></td>
					
						<td>${fieldValue(bean: insuranceInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: insuranceInstance, field: "details")}</td>
					
						<td>${fieldValue(bean: insuranceInstance, field: "insuranceType")}</td>
					
						<td>${fieldValue(bean: insuranceInstance, field: "price")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${insuranceInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/insurance/show.gsp
<%@ page import="smarty2.Insurance" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'insurance.label', default: 'Insurance')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-insurance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-insurance" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list insurance">
			
				<g:if test="${insuranceInstance?.company}">
				<li class="fieldcontain">
					<span id="company-label" class="property-label"><g:message code="insurance.company.label" default="Company" /></span>
					
						<span class="property-value" aria-labelledby="company-label"><g:link controller="insuranceCompany" action="show" id="${insuranceInstance?.company?.id}">${insuranceInstance?.company?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${insuranceInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="insurance.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${insuranceInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${insuranceInstance?.details}">
				<li class="fieldcontain">
					<span id="details-label" class="property-label"><g:message code="insurance.details.label" default="Details" /></span>
					
						<span class="property-value" aria-labelledby="details-label"><g:fieldValue bean="${insuranceInstance}" field="details"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${insuranceInstance?.insuranceType}">
				<li class="fieldcontain">
					<span id="insuranceType-label" class="property-label"><g:message code="insurance.insuranceType.label" default="Insurance Type" /></span>
					
						<span class="property-value" aria-labelledby="insuranceType-label"><g:fieldValue bean="${insuranceInstance}" field="insuranceType"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${insuranceInstance?.price}">
				<li class="fieldcontain">
					<span id="price-label" class="property-label"><g:message code="insurance.price.label" default="Price" /></span>
					
						<span class="property-value" aria-labelledby="price-label"><g:fieldValue bean="${insuranceInstance}" field="price"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:insuranceInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${insuranceInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>